# Generated by Django 4.0.10 on 2023-04-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_password_reset_key_resetpasswordotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordotp',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
