# Generated by Django 4.0.10 on 2023-05-07 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_freepbxoauth2access'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrepbxExtentionProfile',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('freepbx_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('extention_id', models.PositiveIntegerField(unique=True)),
                ('caller_id', models.CharField(max_length=200)),
                ('extention_password', models.TextField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
