# Generated by Django 4.0.10 on 2023-05-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_frepbxextentionprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FrepbxExtentionProfile',
            new_name='FreepbxExtentionProfile',
        ),
    ]
