# Generated by Django 4.0.10 on 2023-05-07 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_frepbxextentionprofile_freepbxextentionprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freepbxextentionprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
