# Generated by Django 4.0.10 on 2023-05-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_freepbxextentionprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freepbxextentionprofile',
            name='freepbx_id',
        ),
    ]
